print('init.lua loaded')
require('basic')
require('keybindings')
require('plugins')

-- 插件配置
require('plugin-config.nvim-tree')
require('plugin-config.nvim-gitsigns')
require('plugin-config.nvim-git-blame')
require('plugin-config.nvim-neogit')
require('plugin-config.nvim-feline')
require('plugin-config.nvim-hop')
require('plugin-config.nvim-comment')
require('plugin-config.nvim-todo-comments')
require('plugin-config.nvim-telescope')
require('plugin-config.nvim-bufferline')
require('plugin-config.nvim-treesitter')
require('plugin-config.nvim-treesitter-context')
require('plugin-config.nvim-autopairs')
require('plugin-config.nvim-indent')
require('plugin-config.nvim-mason')
require('plugin-config.nvim-illuminate')
require('plugin-config.nvim-notify')
require('plugin-config.lsp.init')
require('plugin-config.lsp.lsp-signature')
require('plugin-config.nvim-surround')
require('plugin-config.nvim-dashboard')
require('plugin-config.nvim-substitute')
require('plugin-config.nvim-toggleterm')
require('plugin-config.nvim-cmp')
require('plugin-config.nvim-lspsaga')
require('plugin-config.nvim-fidget')
require('plugin-config.nvim-smooth-cursor')
require('plugin-config.nvim-outline')
